<?php
/**
 * JLDC Theme Functions and Definitions
 *
 * Set up the theme and provide functions to support the theme.
 *
 * @package WordPress
 * @subpackage JLDC_Theme
 * @since JLDC Theme 1.0
 */

/**
 * Removes the generator metatag for security purposes. This way site
 * visitors cannot see that the site is WordPress nor know its version
 *
 * @since JLDC Theme 1.0
 */
remove_action( 'wp_head', 'wp_generator' );

/**
 * Registers and enqueues all scripts and styles for the theme
 *
 * @since JLDC Theme 1.0
 */
function jldc_enqueues() {
	// Register Theme Styles
	wp_register_style( 'jldc-styles', get_stylesheet_uri(), '', '1.0.0', 'screen' ); // Main style

	// Enqueue Styles
	wp_enqueue_style( 'jldc-styles' );

	// Register Scripts
	wp_register_script( 'jldc-header-script', get_stylesheet_directory_uri() . '/_js/jldc-header.js', array( 'jldc-typekit-core' ), null, false );
	wp_register_script( 'jldc-script', get_stylesheet_directory_uri() . '/_js/jldc-script.js', null, null, true );
	wp_register_script( 'jldc-typekit-core', 'https://use.typekit.net/yih1lcp.js', null, null, false );
	wp_register_script( 'jldc-font-awesome', 'https://use.fontawesome.com/72d4cadbab.js', '', '4.6.3', false );

	// Enqueue Scripts
	wp_enqueue_script( 'jldc-header-script' );
	wp_enqueue_script( 'jldc-font-awesome' );
}
add_action( 'wp_enqueue_scripts', 'jldc_enqueues' );

/**
 * Changes the default "Read More" link generated by use of <!-- more --> inside a post
 * to display "Coninue Reading..." instead
 *
 * @return string
 * @since JLDC Theme 1.0
 */
function jldc_read_more_link() {
	return '<a class="more-link" href="' . get_permalink() . '">Continue Reading&#8230;</a>';
}
add_filter( 'jldc_read_more_link', 'modify_read_more_link' );

/**
 * Replaces "[...]" links to "Continue Reading..." when the_excerpt() is used
 *
 * @return string
 * @since JLDC Theme 1.0
 */
function jldc_excerpt_read_more() {
	global $post;
	return '<p><a class="more-link" href="' . get_permalink() . '">Read the Full Article&#8230;</a></p>';
}
add_filter( 'excerpt_more', 'jldc_excerpt_read_more' );


/**
 * Register menus that the WordPress Admin panel will manage
 *
 * @since JLDC Theme 1.0
 */
function jldc_register_menus() {
	register_nav_menus(
		array(
			'main-menu'     => __( 'Main Menu' ),
			'footer-menu'   => __( 'Footer Menu' ),
		)
	);
}
add_action( 'init', 'jldc_register_menus' );

/**
 * Require external file containing custom navigation walker for
 * wp_nav_menu() that produces proper ARIA role attributes in menus
 *
 * @since JLDC Theme 1.0
 */
require( get_stylesheet_directory() . '/_inc/walker.php' );
